---
title: "Home"
toc: false
---

<div class="home-content">

## Welcome!

I'm a cognitive neuroscientist, currently working as a **postdoctoral research fellow** at the Donders Institute \@Nijmegen. My current focus is on the relation between the **gut-microbiome-brain axis**, and uncovering the consequences of **iron deficiency** and **iron overload** on our brain, cognitive and mental health. Take a look at [Projects](projects.qmd) to find out more about my current research projects. Also, feel free to [reach out](contact.qmd) if you want to connect.

In my work, I use a combination of **computational modeling** and **advanced statistical modeling**, to uncover patterns in large multivariate datasets. Therefore, I'm coding a lot in **R/Python**, but mostly standing on the shoulders of the heroes that maintain research packages on Github. Beyond my direct research projects, I have a broad interest in everything science & philosophy! In my Dutch blog [Hersenvoer](hersenvoer.qmd), I write for a broad audience about my work and beyond, check it out!

### A (very) short educational history

Just as my interests are broad, so was my formal education. First, you could find me mainly at the bench, pipetting and centrifuging to discover new drugs during my Bachelor's Pharmaceutical Sciences at Utrecht University. After the course Psychopharmacology, I fell in love with Neuroscience, and decided to pursue a Master's at Neuroscience & Cognition, also at Utrecht University and following that, a cognitive neuroscience PhD at Leiden University, where I tried to find the neuromodulatory underpinnings of why our focus seems so unstable.

</div>
