---
title: "Current Projects"
---

### Dynamics of the Gut-Brain Axis

The Gut-Brain Axis is a hot topic, with the (re)discovery of the importance of the microbes that live in our gut. Using large multimodal datasets, we want to explore the robustness of the links between what microbes we have in our gut and our brain and mental health. This project is embedded in the [European Horizon Project](https://hereditary-project.eu/overview/), which aims to leverage large multimodal datasets to improve patient treatment, while also ensuring privacy compliance.

### Brain Iron Metabolism

Iron is an essential mineral for our body to survive, but in excess it can also be toxic for our bodies. Here, I explore both the consequence of iron deficiency on essential brain processes, like synthesizing neurotransmitters, but also the detrimental effects of brain iron accumulation on cognition and brain health.

### Neuromodulatory Underpinnings of the Variability of Cognitive Control

Why can we sometimes get into a good focus state, while other times we are distracted by even the smallest sound? In my dissertation, we researched the mechanistic underpinnings of this variability in attention and cognitive control by focusing on the neurotransmitter responsible for arousal: noradrenaline.
