---
title: "Current Projects"
---

### Dynamics of the Gut-Brain Axis

The Gut-Brain Axis is a hot topic, with the (re)discovery of the importance of the microbes that live in our gut. Using large multimodal datasets, we want to explore the robustness of the links between what microbes we have in our gut and our brain and mental health. This project is embedded in the [European Horizon HEREDITARY Project](https://hereditary-project.eu/overview/), which aims to leverage large multimodal datasets to improve patient treatment while also ensuring privacy compliance. The work is conducted within the [Memory and Emotion lab](https://www.ru.nl/en/departments/donders-community-for-medical-neuroscience/memory-emotion) at Radboudumc and [the food and cognition group](http://www.esther-aarts.com/) at Radboud University. For this work, I also closely collaborate with the [Cancer Microbiology group](http://boleij-lab.org/) and the [AI for Precision Medicine group](https://www.radboudumc.nl/en/research/research-groups/ai-for-precision-medicine).

### Brain Iron Metabolism

Iron is an essential mineral for our body to survive, but in excess it can also be toxic. Here, I explore both the consequences of iron deficiency on essential brain processes — like the synthesis of neurotransmitters — and the detrimental effects of brain iron accumulation on cognition and brain health. This project runs through a Donders Collaboration Grant, whereby I collaborate with [José Marques](https://www.ru.nl/personen/rebelo-ferreira-marques-j) and [Joukje Oosterman](https://www.ru.nl/personen/oosterman-j) in order to investigate brain iron and cognitive aging in a large, multimodal dataset.

### Neuromodulatory Underpinnings of the Variability of Cognitive Control

Why can we sometimes get into a good focus state, while other times we are distracted by even the smallest sound? In my dissertation, I researched the mechanistic underpinnings of this variability in attention and cognitive control by focusing on the neurotransmitter responsible for arousal: noradrenaline. For this project, I was embedded in the the [Temporal Attention lab](https://sander-nieuwenhuis.github.io/research/) of Sander Nieuwenhuis at Leiden University, and worked in close collaboration with [Bryant Jongkees](https://bryantjongkees.com/) and the [lab of Jonathan D. Cohen](https://sites.google.com/view/ncclab/).
